# Generated by Django 3.1.1 on 2020-10-08 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_pdfs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pdfs',
        ),
    ]
