# Generated by Django 3.1.1 on 2020-10-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='book_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
