# Generated by Django 3.1.1 on 2020-10-08 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201007_0152'),
        ('blog', '0003_auto_20201007_1518'),
    ]

    operations = [
    ]
