# Generated by Django 3.1.1 on 2020-10-08 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_pdfs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pdfs',
        ),
    ]
