# Generated by Django 3.1.1 on 2020-10-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_pdfs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pdfs',
        ),
    ]
