# Generated by Django 3.1.1 on 2020-10-08 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_posts_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='contact',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
