# Generated by Django 3.1.1 on 2020-10-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_posts_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='pdf_file',
            field=models.FileField(default=0, upload_to='pdfs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='pdf_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
